name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Inject API Key
        run: echo "VITE_OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env

      - name: Build Project
        run: npx vite build

      - name: Deploy (Optional)
        run: echo "Deploy step goes here"
